services:
  app:
    # Change to use the local Dockerfile if you want to build the image locally
    #build:
    #  context: .
    #  dockerfile: .docker/Dockerfile
    image: ghcr.io/andrejvysny/spendly:main

    container_name: spendly
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      APP_NAME: "Spendly"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "http://localhost"
      APP_KEY: ${APP_KEY}
      
      # Database
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      
      # Cache and Session
      CACHE_DRIVER: file
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      
      # Mail
      MAIL_MAILER: smtp
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: "${APP_NAME}"
      
      # Logging
      LOG_CHANNEL: stderr
      LOG_LEVEL: error
    volumes:
      - app_storage:/var/www/html/storage
      - app_bootstrap:/var/www/html/bootstrap/cache
      - app_database:/var/www/html/database

volumes:
  app_storage:
    driver: local
  app_bootstrap:
    driver: local
  app_database:
    driver: local
