#!/command/with-contenv sh
cd /app

if [ -n "${SERVER_NAME:-}" ]; then
    export SPENDLY_SERVER_NAME="${SERVER_NAME}, http://127.0.0.1:80"
    export SPENDLY_CADDY_GLOBAL_OPTIONS=""
else
    export SPENDLY_SERVER_NAME=":80"
    export SPENDLY_CADDY_GLOBAL_OPTIONS="auto_https off"
fi

exec php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=80 --admin-port=2019 --caddyfile=/etc/caddy/Caddyfile
